from typing import Protocol


class StorageProvider(Protocol):
    """Dónde viven los archivos. La BD solo guarda la key, nunca URLs."""

    async def put(self, key: str, data: bytes, content_type: str) -> None: ...

    async def get(self, key: str) -> bytes: ...

    async def get_url(self, key: str) -> str: ...

    async def delete(self, key: str) -> None: ...
